import clientPromise from "@/lib/dbConnect";
import { ObjectId } from "mongodb";
import Link from "next/link";


export const metadata = {
  title: "Service Details",
  description: "Generated by Fahmida",
};

export const dynamic = "force-dynamic";

async function getService(service_id) {
  try {
    if (!ObjectId.isValid(service_id)) return null;

    const client = await clientPromise;
    const db = client.db("care_xyz");

    const service = await db
      .collection("services")
      .findOne({ _id: new ObjectId(service_id) });
    return service;
  } catch (error) {
    console.error("Database Error:", error);
    return null;
  }
}

/*  Page Component */
export default async function ServiceDetail({ params }) {
  const { service_id } = await params; 

  const service = await getService(service_id);

  return (
    <div className="max-w-5xl mx-auto p-12 bg-purple-300 min-h-screen">
      <Link
        href="/services"
        className="text-blue-600 hover:underline mb-8 inline-block font-semibold"
      >
        ← Back to Services
      </Link>

      <div className="grid md:grid-cols-2 gap-10 bg-white p-8 rounded-3xl shadow-xl">
        {/* Image Section */}
        <div>
          {service.image ? (
            <img
              src={service.image}
              alt={service.title}
              className="w-full h-96 object-cover rounded-2xl shadow-lg"
            />
          ) : (
            <div className="bg-gray-200 border-2 border-dashed rounded-2xl w-full h-96 flex items-center justify-center text-gray-400">
              No Image Available
            </div>
          )}
        </div>

        {/* Details Section */}
        <div>
          <h1 className="text-4xl font-bold text-pink-600 mb-4">
            {service.title}
          </h1>

          <p className="text-lg text-gray-700 mb-6 leading-relaxed">
            {service.description}
          </p>

          <div className="space-y-4 mb-8">
            <div className="flex justify-between text-lg pb-2">
              <span className="text-gray-600">Price per Day</span>
              <span className="font-bold text-green-600">
                ৳{service.pricePerDay}
              </span>
            </div>

            <div className="flex justify-between pb-2">
              <span className="text-gray-600">Location</span>
              <span className="font-medium">{service.location}</span>
            </div>

            <div className="flex justify-between pb-2">
              <span className="text-gray-600">Availability</span>
              <span className="font-medium text-blue-600">{service.availability}</span>
            </div>

            <div className="flex justify-between">
              <span className="text-gray-600">Rating</span>
              <span className="font-bold text-2xl
               text-yellow-600 flex
                items-center gap-1">
                ⭐ {service.rating}
              </span>
            </div>
          </div>

          {/*  Booking link */}
          <Link
            href={`/booking/${service._id.toString()}`}
            className="w-full block text-center bg-green-600 hover:bg-green-700 text-white font-bold text-xl py-4 rounded-xl transition shadow-lg active:scale-95"
          >
            Book This Service
          </Link>
        </div>
      </div>
    </div>
  );
}